services:
  object-storage:
    build: object_storage
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_BROWSER_REDIRECT_URL=${OBJECT_STORAGE_CONSOLE_URL}
    volumes:
      - object_storage:/data

  discord-bot:
    build: discord_bot
    init: true
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - MAX_UPLOAD_SIZE_MEGABYTES=${MAX_UPLOAD_SIZE_MEGABYTES}
      - ALLOW_ANONYMOUS_UPLOADS=${ALLOW_ANONYMOUS_UPLOADS}
      - WEB_INTERFACE_URL=${WEB_INTERFACE_URL}
      - OBJECT_STORAGE_URL=${OBJECT_STORAGE_URL}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    depends_on:
      - object-storage

  gateway:
    build: gateway
    ports:
      - "443:443"
    depends_on:
      - object-storage
      - discord-bot

volumes:
  object_storage:
